thechausenone/workspace

package.json
src/app/app.module.ts
src/index.html
src/styles.scss

- added Xel as an npm dependency
- Xel is now available to any component under the AppModule

Initial Xel Setup

---

src/index.html

was encountering error due to not loading the stylesheet before the script

bug fix: uncaught type error

---

src/app/components/home/home.component.html
src/app/components/home/home.component.scss
src/app/components/home/home.component.ts

This closes issue #3 for creating a task bar

Create task bar

---

package.json
src/app/app.module.ts
src/app/components/home/home.component.html
src/app/components/home/home.component.scss
src/app/components/home/home.component.ts
src/index.html

Gridster skeleton

---

package.json
src/app/app.module.ts
src/app/components/grid/grid.component.html
src/app/components/grid/grid.component.ts
src/app/components/grid/objects/window.object.ts
src/app/components/navbar/navbar.component.html
src/app/components/navbar/navbar.component.ts
src/app/components/navbar/objects/board.object.ts
src/app/providers/data.service.ts
src/app/providers/electron.service.ts
src/app/providers/mock-data/boards.data.json

This closes #18.
Note: due to the fact that we're using "hot-reloading" for development purposes, writing to the JSON data file causes the whole app to reload. I'm looking into seeing if this issue persists when the app has been packaged into an .exe

18 data service

---

src/app/app.module.ts
src/app/components/navbar/navbar.component.html
src/app/components/navbar/navbar.component.ts

fixed conflicts from previous branch merge

fix for merge conflicts

---

src/app/app.module.ts
src/app/components/navbar/navbar.component.html
src/app/components/navbar/navbar.component.scss

added window menu + changed to sidenav for navbar

---

src/app/components/grid/grid.component.ts
src/app/components/navbar/navbar.component.html
src/app/components/navbar/navbar.component.ts
src/app/providers/data.service.ts
src/app/providers/mock-data/boards.data.json

10 board switching

---

src/app/app.component.html
src/app/app.component.scss
src/app/components/board-dialog/board-dialog.component.scss
src/app/components/grid/grid.component.html
src/app/components/grid/grid.component.scss
src/app/components/grid/grid.component.ts
src/app/components/navbar/navbar.component.html
src/app/components/navbar/navbar.component.scss
src/styles.scss

cleaned up existing css to use proper nesting, mixins, and variables where applicable. this closes #43.

refactor css

---

src/app/app.module.ts
src/app/components/navbar/navbar.component.scss
src/app/components/navbar/navbar.component.ts
src/app/shared/shared.module.ts

44 shared module

---

src/app/components/window-dialog/window-dialog.component.html
src/app/components/window-dialog/window-dialog.component.scss
src/app/components/window-dialog/window-dialog.component.ts

Fixed errors that occured when opening up the window dialog

Fixed window dialog errors

---

src/app/app-routing.module.ts
src/app/modules/login/components/login/login.component.html
src/app/modules/login/components/login/login.component.scss
src/app/modules/login/components/signup/signup.component.html
src/app/modules/login/components/signup/signup.component.scss
src/app/modules/login/components/signup/signup.component.spec.ts
src/app/modules/login/components/signup/signup.component.ts
src/app/modules/login/login.module.ts

57 add signup component

---

src/app/app.module.ts
src/app/components/grid/grid.component.html
src/app/components/grid/grid.component.scss
src/app/components/grid/grid.component.ts
src/app/components/home/home.component.scss
src/app/components/main/main.component.scss
src/app/components/navbar/navbar.component.html
src/app/components/navbar/navbar.component.scss
src/app/components/navbar/navbar.component.ts
src/app/modules/login/components/login/login.component.scss
src/app/modules/shared/shared.module.ts
src/app/pipes/title-length.pipe.ts
src/app/providers/data.service.ts
src/app/providers/mock-data/boards.data.json
src/styles.scss

64 restyle app

---

src/app/components/navbar/navbar.component.html
src/app/components/navbar/navbar.component.scss
src/app/components/navbar/navbar.component.ts
src/app/modules/shared/shared.module.ts

Added dropdown menu for boards

---

src/app/components/navbar/navbar.component.html

This closes #41 
Thanks David for basically doing this ticket for me lol

Delete board in board menu

---

src/app/components/navbar/navbar.component.ts
src/app/providers/data.service.ts
src/app/providers/electron.service.ts

Uses data service to open board programs

---

main.ts
src/app/app.module.ts
src/app/components/main/main.component.html
src/app/components/main/main.component.scss
src/app/components/menubar/menubar.component.html
src/app/components/menubar/menubar.component.scss
src/app/components/menubar/menubar.component.spec.ts
src/app/components/menubar/menubar.component.ts
src/app/components/navbar/navbar.component.scss
src/app/modules/login/components/signup/signup.component.scss

30 new toolbar

---

src/app/components/navbar/navbar.component.html
src/app/components/navbar/navbar.component.scss
src/app/components/navbar/navbar.component.ts

issue was that newest board wasn't getting focused on
this closes #86

Fixed focus issue after board creation

---

src/app/app.component.html
src/app/app.component.scss
src/app/components/main/main.component.html
src/app/components/main/main.component.scss
src/app/components/menubar/menubar.component.scss
src/styles.scss

moved app-menubar selector to AppComponent
this closes #82

Fixed issue with menubar not displaying on login screens

---

src/app/components/home/home.component.ts
src/app/components/menubar/menubar.component.html
src/app/components/menubar/menubar.component.ts
src/app/providers/electron.service.ts

- now contains "report a bug" instead of "tutorial"
- "about" and "report a bug" are both linked to pages
- removed "Help" from menubar

Updated homescreen w/ new links

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/home/home.component.ts
src/app/modules/settings/components/settings-page/settings-page.component.html
src/app/modules/settings/components/settings-page/settings-page.component.scss
src/app/modules/settings/components/settings-page/settings-page.component.spec.ts
src/app/modules/settings/components/settings-page/settings-page.component.ts
src/app/modules/settings/settings.module.ts

- HomeComponent's settings button will link to this new component
- no configurable settings implmenented as of yet
this closes #105 and #39

Created SettingsPageComponent

---

electron-builder.json
src/app/providers/electron.service.ts

Fixed "Activate Board" for packaged version of app

---

src/app/modules/login/components/login/login.component.ts

Changed error message + changed routing after login
